Search engine init project setup
devblogs-ir/Twitter.Clone pull request #128
Opened 2024-02-16 17:46 UTC by arezookmn

Change project structure from clean to simpler structure

2024-02-17 16:04 UTC, Javidleo commented on src/services/search-engine/Twitter.Clone.Search.WebApi/ConfigureServices.cs
> +    public static IServiceCollection RegisterServices(this IServiceCollection services)
this is good, but it can get better, please create a new directory named DI and create a separate class for each concern dependencies, it would be named like this: 
- ApplicationDependencyInjection and method name would be: RegisterApplicationServices
- InfrastructureDependencyInjection and method would be : RegisterInfrastructureServices

2024-02-17 16:05 UTC, Javidleo commented on src/services/search-engine/Twitter.Clone.Search.WebApi/ConfigureServices.cs
> +        services.AddDbContext<ApplicationDbContext>();
put repository and dbcontext di configurations in Infrastructure and Services Di configurations in Application.

2024-02-17 16:08 UTC, Javidleo commented on src/services/search-engine/Twitter.Clone.Search.WebApi/Context/Configurations/HashtagConfigurations.cs
> +    {
please don't ever push code with not implemented exception.

2024-02-17 16:11 UTC, Javidleo commented on src/services/search-engine/Twitter.Clone.Search.WebApi/Context/Configurations/TweetConfigurations.cs
> +        builder.HasMany(e => e.Hashtags)
for many to many relations you need to have two configurations, one in each side of relation entities.
one of them make one to many relation between Hashtag and TweetHashtag 
and the other one make one to many relation between Tweet and TweetHashtag,
advice : create a configuration file for TweetHashtag and add both configurations there.

2024-02-17 16:12 UTC, Javidleo commented on src/services/search-engine/Twitter.Clone.Search.WebApi/Entities/Hashtag.cs
> +    public List<Tweet> Tweets { get; set; } = [] ;
In many to many relations, you only need to know the Intermediary table from each side, so you don't need a list of Tweet in Hashtag. and also a list of Hashtag in Tweet

2024-02-17 16:13 UTC, Javidleo commented on src/services/search-engine/Twitter.Clone.Search.WebApi/Entities/TweetHashtag.cs
> +}
as you did not set a primary key for this Entity, please add one or create a compound key for it .

2024-02-17 16:15 UTC, Javidleo commented on src/services/search-engine/Twitter.Clone.Search.WebApi/Entities/Tweet.cs
> +{
for all of the Entity classes, change the `set` accessor to private 
example : public string Content { get; private set;}

2024-02-17 16:19 UTC, Javidleo requested changes
please change all the requested comments and send back for another review.

2024-02-17 19:12 UTC, arezookmn commented on src/services/search-engine/Twitter.Clone.Search.WebApi/ConfigureServices.cs
> +    public static IServiceCollection RegisterServices(this IServiceCollection services)
ok

2024-02-17 19:35 UTC, arezookmn commented on src/services/search-engine/Twitter.Clone.Search.WebApi/Entities/Tweet.cs
> +{
Can I use init instead of private set?

2024-02-19 05:34 UTC, Javidleo requested changes
please remove the solution from our search engine application, all the applications should use the base solution file and add search engine application to that solution. 
for that, open the base solution and add a new folder named : search-engine and add existing project (search-engine)

2024-02-19 06:19 UTC, Javidleo commented
Hey @thisisnabi can you review my review? 
I want to make sure that I did not missed something.

2024-02-19 06:26 UTC, thisisnabi commented
> Hey @thisisnabi can you review my review? I want to make sure that I did not missed something.

As a lead, first approve this PR and then ask us. 

There is still a change request in this PR, which apparently has not been done? please check it.

2024-02-19 06:34 UTC, Javidleo commented
> > Hey @thisisnabi can you review my review? I want to make sure that I did not missed something.
> 
> As a lead, first approve this PR and then ask us.
> 
> There is still a change request in this PR, which apparently has not been done? please check it.
no I just wanted to know

2024-02-19 07:21 UTC, Javidleo requested changes
also remove the ApplicationDbContext class and rebuild project it has some errors. 
I pulled your branch and it removed the trends project from my solution, check that if you don't have trend application in your solution.

2024-02-19 07:39 UTC, Javidleo approved these changes
its ok now,

2024-02-19 07:40 UTC, Javidleo commented
I approved the changes @thisisnabi, we remove all unnecessary files for init project setup task.

2024-02-20 20:40 UTC, Javidleo commented
@thisisnabi 
We are still waiting

2024-02-23 00:18 UTC, thisisnabi commented
This branch has conflicts that must be resolved @Javidleo 

I see a lot of sloppiness in this brunch. You can rebase this branch and add your changes quickly.

>[!Warning]
>the name of your project should be this
`Twitter.Clone.SearchEngine.......`

2024-02-23 11:45 UTC, thisisnabi commented
@arezookmn: **This branch has conflicts that must be resolved**

2024-02-23 11:48 UTC, thisisnabi requested changes
Your project must be in this path `src\services\search-engine`

2024-02-23 20:03 UTC, merged